# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38a2bfbbab623ad39c1fd16e2d2866b7685efb09f9aa810a24fd6b9a4be305a2120dd6f94a32594785439905aee4f8da8be5c425c9fd5d8d8b1fd73c1ff715ad

test:
  secret_key_base: f806cd8d5177054fcb96805b0331286bb382a030d2354d16fdfa88151038177c9f231ff6cf6785ebcaaed88498f0b8596fa2503a565aa48d12028b5dd24d60a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
